name: CAMF
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310hcf8288c_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.5.2=py310h7c4b9e2_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.1.0
      - babel==2.17.0
      - black==25.1.0
      - certifi==2025.1.31
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - distlib==0.3.9
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - future==1.0.0
      - ghp-import==2.1.0
      - griffe==1.5.6
      - huggingface-hub==0.28.1
      - hyperopt==0.2.7
      - identify==2.6.7
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-exec==1.10.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mergedeep==1.3.4
      - mike==2.1.3
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.3.0
      - mkdocs-gen-files==0.5.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-glightbox==0.4.0
      - mkdocs-literate-nav==0.6.1
      - mkdocs-material==9.6.3
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.28.0
      - mkdocstrings-python==1.14.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==2.2.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - packaging==24.2
      - paginate==0.5.7
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - py4j==0.10.9.9
      - pygments==2.19.1
      - pygments-ansi-color==0.3.0
      - pymdown-extensions==10.14.3
      - pyparsing==3.2.1
      - pytest==8.3.4
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - rdkit==2024.9.5
      - regex==2024.11.6
      - requests==2.32.3
      - ruff==0.9.6
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.12.2
      - sympy==1.13.1
      - tabpfn==2.0.5
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - torch==2.5.0
      - torch-geometric==2.6.1
      - torchaudio==2.5.0
      - torchvision==0.20.0
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - verspec==0.1.0
      - virtualenv==20.29.1
      - watchdog==6.0.0
      - yarl==1.18.3
      - zipp==3.21.0
